version: '3.4'

services:
  exodusgym_api:
    image: ${DOCKER_REGISTRY-}exodusgymapi
    ports:
    - "5000:80"
    - "5001:443"
    build:
      context: .
      dockerfile: ExodusGym_API/Dockerfile
    
  sql-server-exodusdb:
    container_name: sql-server-exodusdb
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "ExodusGym123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"