export const GET_MEALS = "GET_MEALS"
export const ADD_MEAL = "ADD_MEAL"
export const UPDATE_MEAL = "UPDATE_MEAL"
export const DELETE_MEAL = "DELETE_MEAL"

export const SET_DAY = "SET_DAY"

export const GET_WORKOUTS = "GET_WORKOUTS"
export const PURCHASE_WORKOUT = "PURCHASE_WORKOUT"
export const ADD_USER_WORKOUT = "ADD_USER_WORKOUT"
export const CREATE_USER_WORKOUT = "CREATE_USER_WORKOUT"
export const UPDATE_WORKOUT = "UPDATE_WORKOUT"
export const DELETE_WORKOUT = "DELETE_WORKOUT"

export const NEW_NOTIFICATION = "NEW_NOTIFICATION"
export const HIDE_HOTIFICATION = "HIDE_NOTIFICATION"

export const TOGGLE_WORKOUT_MODAL = "TOGGLE_WORKOUT_MODAL"